### ISSUE TITLE
SSO timeout

### ISSUE THREAD

**Issue by morancj** [linaro-its/aws2-wrap#11]
In my Terraform repo, I have:

```zsh
➜ pipenv graph
aws2-wrap==1.0.2
➜ pipenv run pip list
Package    Version
---------- -------
aws2-wrap  1.0.2
pip        19.3.1
setuptools 42.0.2
wheel      0.33.6
➜ aws sso login --profile=SSO_Terraform
Attempting to automatically open the SSO authorization page in your default browser.
If the browser does not open or you wish to use a different device to authorize this request, open the following URL:

https://device.sso.us-east-1.amazonaws.com/

Then enter the code:

ABCD-EFGH
...snip...
Successully logged into Start URL: https://linaro.awsapps.com/start
➜ pipenv run aws2-wrap --profile SSO_Terraform --export
export AWS_ACCESS_KEY_ID="ASIA<REDACTED>"
export AWS_SECRET_ACCESS_KEY="<REDACTED>"
export AWS_SESSION_TOKEN="<REDACTED>"
```

This works fine, but the credentials expire after some time.
In my `~/.aws/sso/cache/<REDACTED>.json:

```json
{
   "accessToken" : "<REDACTED>",
   "expiresAt" : "2020-02-20T18:49:27UTC",
   "region" : "us-east-1",
   "startUrl" : "https://linaro.awsapps.com/start"
}
```

Local time when running this was approximately 3.5 hours before `expiresAt`. I get this error:

```zsh
➜ pipenv run aws2-wrap --profile SSO_Terraform --export
An error occurred (UnauthorizedException) when calling the GetRoleCredentials operation: Session token not found or invalid

Please login with 'aws sso login --profile=SSO_Terraform'
```

**Comment by pcolmer** [comment]
Testing shows that the `UnauthorizedException` error occurs one hour after the login process. This suggests that there might still be a bug in AWS SSO which, until recently, wasn't honouring the session duration correctly and was always expiring after an hour.

I'll contact AWS and see what they say.

**Comment by morancj** [comment]
Thanks for verifying this @pcolmer

**Comment by morancj** [comment]
@pcolmer BTW, here's my `aws-cli` version information:

```zsh
➜ aws --version            
aws-cli/2.0.0 Python/3.7.3 Linux/5.4.15-arch1-1 botocore/2.0.0dev4
```

**Comment by pcolmer** [comment]
Repeating the test process (below) seems to now work beyond the 1 hour period:

```
aws sso login --profile <profile> (once only)
aws --profile <profile> s3 ls (to show that the CLI side of things continues to work)
aws2-wrap --profile <profile> --export (to show that GetRoleCredentials continues to work)
```

Need to try this closer to 4 hours to see if it is really working. If it is, then need to try to reproduce it with `SSO_Terraform` profile.

**Comment by pcolmer** [comment]
After testing today, I'm pretty happy that the tool is able to continue to get tokens for many hours after the initial login step.

@morancj happy to close?

**Comment by morancj** [comment]
@pcolmer Yes, thank you! It seems the problem was AWS' end, and has now been resolved. Thanks for the follow-up.
