### ISSUE TITLE
make this a credential_process ?

### ISSUE THREAD

**Issue by flyinprogrammer** [linaro-its/aws2-wrap#17]
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html

You might consider making this a `credential_process` so that then most aws sdks can just naturally source credentials via an AWS_PROFILE - which also means, auto-magic credential renewals (assuming your SSO login hasn't expired).

I wrote a version of this in golang (to avoid the os dependency requirements): https://github.com/flyinprogrammer/aws-sso-fetcher

Thanks for making this code base, it made writing my code very straightforward, and obviously feel free to instantly close this issue, it's just 2 cents from another human.

**Comment by pcolmer** [comment]
Thanks for the suggestion, @flyinprogrammer. I'll take a look at that.

**Comment by pcolmer** [comment]
This has been implemented - many thanks for the suggestion.
