### ISSUE TITLE
How to use commands with quotes?

### ISSUE THREAD

**Issue by stefan-van-de-griendt-quandago** [linaro-its/aws2-wrap#20]
I've been banging my head around why `aws2-wrap` can't seem to properly propagate quotes. In this case I'm using Terraform and no matter what I try, I'll always get either an `aws2-wrap` error about an invalid `--exec` argument or an error in Terraform stating it's not receiving a properly named variable.

`aws2-wrap` error
> Command 1: `aws2-wrap --profile "terraform" --exec "terraform state mv 'aws_cloudfront_origin_access_identity.origin_access_identity' 'module.platform.aws_cloudfront_origin_access_identity.this[""The Name""]'"`
> Command 2: aws2-wrap --profile "terraform" --exec "terraform state mv aws_cloudfront_origin_access_identity.origin_access_identity module.platform.aws_cloudfront_origin_access_identity.this[""The Name""]"
> Error: aws2-wrap: error: unrecognized arguments: Name]'

Terraform error
> Command 1: `aws2-wrap --profile "terraform" --exec "terraform state mv 'aws_cloudfront_origin_access_identity.origin_access_identity' 'module.platform.aws_cloudfront_origin_access_identity.this[\"The Name\"]'"`
> Command 2: `aws2-wrap --profile "terraform" --exec "terraform state mv aws_cloudfront_origin_access_identity.origin_access_identity module.platform.aws_cloudfront_origin_access_identity.this[\"The Name\"]"`
> Error 1: Single quotes are not valid. Use double quotes (") to enclose strings.
> Error 2: Index brackets must contain either a literal number or a literal string.

Command I'm trying to execute in PowerShell (note the space in, as `aws2-wrap` doesn't seem to like it too much either)
- Terraform: `terraform state mv aws_cloudfront_origin_access_identity.origin_access_identity module.platform.aws_cloudfront_origin_access_identity.this["The Name"]`
- `aws2-wrap`: `aws2-wrap --profile "terraform" --exec "terraform state mv aws_cloudfront_origin_access_identity.origin_access_identity module.platform.aws_cloudfront_origin_access_identity.this[""This Name""]"`

I've tried putting the `--exec` into a variable and matching the `state mv` argument as shown on https://www.terraform.io/docs/commands/state/mv.html. But that won't work either (only seems to throw the Terraform error though). Note that I've checked the contents of the variable, and they match with what you'd expect (tried all variations above). Also tried wrapping the entire variable in another set of quotes (both single and double), but it didn't work either...

When trying something like the following, I even get a Terraform error. It really looks like `aws2-wrap` is doing something with quotes and seems to even change them from `"` to `'` at times. I assume this, because even when I'm not using any `'`, Terraform stil complains about it.
`aws2-wrap --profile "terraform" --exec "terraform state mv 'aws_cloudfront_origin_access_identity.origin_access_identity' 'module.platform.aws_cloudfront_origin_access_identity.this[The Name]'"`

I'd like to know how to execute the Terraform command with `aws2-wrap` and unfortunately the Internet doesn't seem to know either.

**Comment by stefan-van-de-griendt-quandago** [comment]
A little update: I've totally overlooked the first part of Terraform's TRACE. It contains some vital information of what command it receives. Also note that I'm using `aws2-wrap` 1.0.3 (seems to be the latest).

Command: ` aws2-wrap --profile "terraform" --exec "terraform state mv aws_cloudfront_origin_access_identity.origin_access_identity module.platform.aws_cloudfront_origin_access_identity.this[""The Name""]"`
CLI report: `CLI args: []string{"C:\\Program Files\\Terraform\\terraform.exe", "state", "mv", "aws_cloudfront_origin_access_identity.origin_access_identity", "module.platform.aws_cloudfront_origin_access_identity.this[The"}`
Error Terraform: `Index brackets must contain either a literal number or a literal string.`
Same without `--exec` (undocumented feature since #13 ?)

Command: `aws2-wrap --profile "terraform" --exec "terraform state mv 'aws_cloudfront_origin_access_identity.origin_access_identity' 'module.platform.aws_cloudfront_origin_access_identity.this[""The Name""]'"`
CLI report: `CLI args: []string{"C:\\Program Files\\Terraform\\terraform.exe", "state", "mv", "'aws_cloudfront_origin_access_identity.origin_access_identity'", "'module.platform.aws_cloudfront_origin_access_identity.this[The"}`
Error Terraform: `Single quotes are not valid. Use double quotes (") to enclose strings.`

Command: `aws2-wrap --profile "terraform" "terraform state mv 'aws_cloudfront_origin_access_identity.origin_access_identity' 'module.platform.aws_cloudfront_origin_access_identity.this[""The Name""]'"`
CLI report: `CLI args: []string{"C:\\Program Files\\Terraform\\terraform.exe", "state", "mv", "'aws_cloudfront_origin_access_identity.origin_access_identity'", "'module.platform.aws_cloudfront_origin_access_identity.this[The", "Name]'"}`
Error Terraform: `Exactly two arguments expected.`

**Comment by pcolmer** [comment]
Hi @stefan-van-de-griendt-quandago 

I haven't tried this on a Windows system as I use WSL and keep Python, terraform, etc there.

There is an alternative syntax for the command that may help:

`AWS_PROFILE=MySSOProfile aws2-wrap terraform plan`

but I think the `AWS_PROFILE=` part may need altering for that to work on Windows. It may be simpler to set it with:

`SET AWS_PROFILE=MySSOProfile`

then run the rest of the command separately:

`aws2-wrap terraform plan`

**Comment by stefan-van-de-griendt-quandago** [comment]
@pcolmer Thanks for the suggestion, I didn't think of that.

Unfortunately the suggestion of setting the environment variable `AWS_PROFILE` didn't do the trick. To make sure PowerShell wasn't interfering with the double quotes (`"`); I also tried it with `cmd`. Find below an example where I changed the resource name from `this` to `all` and am able to `terraform state mv` the `aws_iam_role`, but not the `aws_iam_role_policy_attachment` because they're created with `for_each` and thus require a string enclosed with double quotes (`"`).

**PowerShell**
```
$env:AWS_PROFILE="Development"
aws2-wrap terraform state mv module.conversation_api.module.dynamodb.module.security.aws_iam_role_policy_attachment.this["answers"] module.conversation_api.module.dynamodb.module.security.aws_iam_role_policy_attachment.all["answers"]
```

**cmd**
```
set AWS_PROFILE=Development
aws2-wrap terraform state mv module.conversation_api.module.dynamodb.module.security.aws_iam_role_policy_attachment.this["answers"] module.conversation_api.module.dynamodb.module.security.aws_iam_role_policy_attachment.all["answers"]
```

Note that here there aren't spaces, but that doesn't matter because the double quotes (`"`) always seem to be removed and Terraform **requires** those double quotes (`"`).

With `cmd` I can do the following, showing that indeed double quotes (`"`) are removed in a very simple set of test cases. Note that the last will keep the double quote (`"`), but when applied to `terraform state mv` it yields the same error. Probably because `echo` is doing something special.
```
# prints: hello
echo hello

# prints: hello (")
echo hello (")

# prints: hello ()
aws2-wrap echo hello (")

# prints: 'hello ()'
aws2-wrap echo 'hello (")'

# prints: hello (")
aws2-wrap echo hello (\")
```

Result for `cmd` using the `\"` technique (note that the double quotes (`"`) are again missing)
```
2020/07/20 11:21:46 [INFO] CLI args: []string{"terraform.exe", "state", "mv", "module.conversation_api.module.dynamodb.module.security.aws_iam_role_policy_attachment.this[answers]", "module.conversation_api.module.dynamodb.module.security.aws_iam_role_policy_attachment.all[answers]"}
```

Additional attempt:
- Wrapped `module...["answers"]` around `'` without `\` --> `'module...["answers"]'` --> 'Single quotes are not valid. Use double quotes (") to enclose strings.'

**Comment by pcolmer** [comment]
Hi

I've done some digging and this seems to be an issue between Windows and Python.

`aws2-wrap` uses `argparse` to convert what you type on the command line into parameters it can understand. Essentially, that command line gets put into `argv` and then `argparse` interprets it.

So, if I run the following on PowerShell:

```
$env:AWS_PROFILE="Development"
aws2-wrap echo "`"foo`""
```

then `aws2-wrap` **should** emit this:

"foo"

But it doesn't. The reason it doesn't is because, despite escaping the double-quotes, they don't reach the script. If you add:

`print(sys.argv[1:])`

just above `args = process_arguments()` and re-run the script, you get this:

`['echo', 'foo']`

confirming that the double-quotes don't reach the script.

Similarly, if you try it from CMD ...

`aws2-wrap echo ""foo""`

you get the same values passed to argv. That seems to suggest this is a bug with Python for Windows, but I can't be 100% certain.

**Comment by pcolmer** [comment]
@stefan-van-de-griendt-quandago 

Can you please try `\\\"` wherever you need a double-quote?

What **might** be happening is that although `CMD` allows escaping of the double-quote with `\"`, I'm not sure how that gets presented to the `os.system` call ... so it may be worth double-escaping so that the `os.system` call gets passed `\"` instead of `"`.

From powershell, I got `'\this is a test'` to resolve to `"this is a test` ... so that might be worth trying.

**Comment by stefan-van-de-griendt-quandago** [comment]
I'm so sorry that it's taking so long, but I don't have time these days to try this out (nor have a direct need for it either). I have noticed that for various things running with `--process` helps and creating a 'wrapped' profile/credentials using `credential_proces` together with it.

I **will** come back to this, but not sure when exactly. Again sorry it's taking so extremely long...

**Comment by pcolmer** [comment]
Hi @stefan-van-de-griendt-quandago 

Not a problem - I often find myself in the same position :).

To be honest, this isn't a problem with aws2-wrap. It is more to do with how PowerShell/CMD process double-quotes and how to properly "escape" them so that they are then passed on to Python.

I'm happy to keep this open to share ideas and solutions but do please understand that there is nothing I can change in the code itself because, as explained previously, the quotes aren't even making it to the script.

**Comment by stefan-van-de-griendt-quandago** [comment]
Today I've got the time to do some checks (and also needed this, so that was convenient).
My workaround is to not use `aws2-wrap` with Terraform at all and use environment variables instead. This allows me to directly use `terraform import` without issues.

To make it easier for me (I have quite a few AWS SSO profiles), I've created multiple PowerShell profiles using Windows Terminal. I then set the following environment variables (of course the AWS profile is different for each one)
- `AWS_PROFILE="TerraformWrapped"`
- `AWS_SDK_LOAD_CONFIG=1`

To make the login for AWS SSO CLI also easier, in the PowerShell script I also added the following check
```powershell
# Check if already logged in with AWS CLI SSO (this is only needed once for the user)
$alreadyLoggedIn = aws sts get-caller-identity
if ($null -eq $alreadyLoggedIn) {
  aws sso login --profile $awsProfile
}
```

The `TerraformWrapped` AWS profile is a trick in your documentation. I've added it as a profile to my AWS config file
```txt
[profile TerraformWrapped]
credential_process = aws2-wrap --process --profile Terraform
region = eu-central-1
```

In PowerShell I was able to `terraform import` with quotes conform the Terraform documentation. Import here are the single quotes (`'`) and slashes before the double quotes (`\"`).
```powershell
terraform import 'aws_route53_record.dev[\"web"\]' importvalue
```

Thanks for your patience and honestly, not having to type `aws2-wrap` in front of every Terraform command works so much nicer! Anybody wondering how I achieved multiple PowerShell profiles with different configuration? Just create a script that checks a variable that you set when you launch PowerShell (in my case through Windows Terminal).
```bat
cmd /c "set "CUSTOM_PROFILE_NAME=Terraform" & pwsh.exe -NoLogo"
```

**Comment by pcolmer** [comment]
Thanks for sharing, @stefan-van-de-griendt-quandago.

I agree that using the `credential_process` feature is by far and away the simplest way to enable SSO use via `aws2-wrap` with - as far as I can tell - *any* application that understands AWS profiles other than SSO profiles. Much simpler than running it all on the same command.
