### ISSUE TITLE
Issue with Quotes in Environment Variables

### ISSUE THREAD

**Issue by MartinLoeper** [linaro-its/aws2-wrap#29]
When I run `$(pipenv run aws2-wrap --profile sso --export)`, the AWS environment variables contain quotes, e.g.:
`AWS_SECRET_ACCESS_KEY="XXXXXXXXXX"`.

Somehow my AWS CLI with version *aws-cli/2.0.22 Python/3.7.3 Linux/5.4.0-58-generic botocore/2.0.0dev26* does not parse the quotes env vars properly.

I have to use the following workaround to strip the quotes from the env vars: `$(env | grep AWS | tr -d '"' | sed -e 's/^/export /')`.

Is this an issue which is specific to my distro or is this a bug in this package?

**Comment by pcolmer** [comment]
Hi @MartinLoeper 

Thanks for reporting this.

I'll take a look at the code and try to fix it.

**Comment by pcolmer** [comment]
@MartinLoeper I've fixed this in version 1.1.4

**Comment by MartinLoeper** [comment]
Thanks for looking into this @pcolmer! Then it's just my pip3 package which is not up to date yet for some reason.

**Comment by pcolmer** [comment]
@MartinLoeper

> Then it's just my pip3 package which is not up to date yet for some reason.

`pip3 install --upgrade aws2-wrap` should do the trick. I published v1.1.4 at the same time as posting the comment: https://pypi.org/project/aws2-wrap/
