### ISSUE TITLE
Add support for AWS CLI v2 through Docker

### ISSUE THREAD

**Issue by brskq** [linaro-its/aws2-wrap#37]
Hi Linaro team and thank you for a great tool!

I noticed the AWS CLI dependency whilst writing documentation on a system which is using the [official AWS CLI version 2 Docker image](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-docker.html) rather than the regular Windows or Linux binary. I installed the [AWS CLI for Windows](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-windows.html) but still had issues as it wouldn't show up in with $PATH. It would be great if we could have an argument to specify the path to the AWS CLI v2 binary **or** the Docker command which could be inserted.

Linux and macOS:

```sh
docker run --rm -it -v ~/.aws:/root/.aws amazon/aws-cli COMMAND
```

Windows PowerShell:

```ps
docker run --rm -it -v $env:userprofile\.aws:/root/.aws amazon/aws-cli COMMAND
```

Relevant code:

```py
    result = subprocess.run(
        [
            "aws", "sso", "get-role-credentials",
            "--profile", profile_name,
            "--role-name", sso_role_name,
```

**Comment by pcolmer** [comment]
Hello @brskq 

Have you tried the steps at https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-docker.html#cliv2-docker-aliases? This essentially "translates" the `aws` command into the required steps to run it within the container so it should then allow the aws2-wrap script to run.

**Comment by pcolmer** [comment]
@brskq Did the AWS documentation help or is there still an issue to be worked on here?
