### ISSUE TITLE
Add installation instructions for pip

### ISSUE THREAD

**Issue by jscook2345** [linaro-its/aws2-wrap#4]
The `README.md` installation section says that `aws2-wrap` can be installed with `pip`, but it does not give an example nor does it include the `pypi` URL. It would be nice to include those so the user does not have to find that information themselves, even if a logical guess would get them there.

Example:
```
# https://pypi.org/project/aws2-wrap
pip install aws2-wrap==1.0.0
```

I can open a pull request for this, but wanted to make sure you agreed with my idea first.

Thanks!

**Comment by pcolmer** [comment]
Hi Justin

More than happy for you to submit a pull request :). Thanks for the suggestion.

Philip
