### ISSUE TITLE
Document breaking changes

### ISSUE THREAD

**Issue by sodul** [linaro-its/aws2-wrap#40]
Thank you for the package, it is quite useful.

We have been using aws2-wrap as a library since version 1.0.2 and the release are often backward incompatible. We had to update our client code when we upgraded to 1.0.3. Now to upgrade to 1.1.11 we have to check what the code changes are to ensure compatibility.

Notably aws2wrap.get_role_credentials() changes are causing issues.

**Comment by pcolmer** [comment]
@sodul Thank you for bringing this to my attention. It never occurred to me that it would be used as a library :)

I will try to find the time to actually document the parameters to each function as a reminder to myself that these should not change and, if they do, to flag them up.

Thanks again.
