### ISSUE TITLE
Version 1.2 throws error

### ISSUE THREAD

**Issue by gerasym** [linaro-its/aws2-wrap#45]
aws2-wrap --profile dev terraform init 

> Traceback (most recent call last): 
>  File "/usr/local/bin/aws2-wrap", line 8, in <module>
>    sys.exit(main())
>TypeError: main() missing 1 required positional argument: 'argv'

**Comment by pcolmer** [comment]
Thank you for letting me know about this, and my apologies.

Fixed in https://github.com/linaro-its/aws2-wrap/pull/46 and released as version 1.2.1.

**Comment by gerasym** [comment]
Thanks for quick fix :)
With 1.2.1 it works with --exec flag only
without i get the following error
aws2-wrap --profile dev terraform init -backend-config=bucket=bucket-name -var-file=config/test.tfvars
terraforminit-backend-config=bucket=bucket-name-var-file=config/test.tfvars: No such file or directory

**Comment by passing** [comment]
I guess the problem is here:
https://github.com/linaro-its/aws2-wrap/blob/master/aws2wrap/__init__.py#L375
arguments need to be joined with a space

**Comment by pcolmer** [comment]
Thanks, @passing. That is a change that got introduced this morning to quickly fix a problem introduced elsewhere. I'll make the fix.

**Comment by pcolmer** [comment]
Fixed in v1.2.2.

**Comment by sodul** [comment]
The bug was my doing, sorry about that!
