### ISSUE TITLE
Add support for sso-session section in AWS config

### ISSUE THREAD

**Issue by jtgasper3** [linaro-its/aws2-wrap#68]
Getting an error: `'sso_start_url' not found in profile: {'sso_session': 'my-sso', 'sso_role_name': 'AdministratorAccess', 'region': 'us-east-1', 'output': 'json', 'profile_name': 'admin'}`

The missing settings are in the "shared" config in the `sso-session` section of the file and are inherited by the profile via the `sso_session` property.

See https://docs.aws.amazon.com/sdkref/latest/guide/feature-sso-credentials.html#sso-token-config
https://docs.aws.amazon.com/sdkref/latest/guide/file-format.html#file-format-config

**Comment by pcolmer** [comment]
Thanks. It looks like AWS have extended the definition of the config file. I'll try to find some time to get a fix in place.

**Comment by pcolmer** [comment]
Hi - fixed in version 1.3.1.

Regards

Philip
