### ISSUE TITLE
Use dependabot or renovatebot to keep dependencies up to date

### ISSUE THREAD

**Issue by nitrocode** [linaro-its/aws2-wrap#74]
Dependencies in

* dev-requirements.txt - python dependencies - this can be covered by dependabot and renovatebot
* github/workflows/ci.yml - actions versions - this can be covered by dependabot and renovatebot
* github/workflows/ci.yml - python version - this i think can only be cover

**Comment by pcolmer** [comment]
Thanks, @nitrocode. dependabot was already enabled for this repository.

**Comment by nitrocode** [comment]
Dependabot has never created a pr in this repo

There are GitHub actions that are out of date

Enabling dependency alerts on the repo is the first step, the second step is adding dependabots configuration file which is usually in the .github/ directory.

Please consider configuring one of the bots so automated prs can be raised.

**Comment by nitrocode** [comment]
cc: @pcolmer

**Comment by pcolmer** [comment]
@nitrocode I'm open to pull requests ... :)
